export const SPECIALTIES = [
  {
    id: 'rheumatology',
    name: 'Rheumatology',
    short: 'rheum',
    graphic: require('../../assets/images/SpecialtyIcons/rheumprorx.png'),
    logo: require('../../assets/images/SpecialtyIcons/Logo/rheumprorx.png'),
    code: 'RHEUM',
  },
  {
    id: 'gastroenterology',
    name: 'Gastroenterology',
    short: 'gastro',
    graphic: require('../../assets/images/SpecialtyIcons/gastroprorx.png'),
    logo: require('../../assets/images/SpecialtyIcons/Logo/gastroprorx.png'),
    code: 'GASTRO',
  },
  {
    id: 'dermatology',
    name: 'Dermatology',
    short: 'derm',
    graphic: require('../../assets/images/SpecialtyIcons/dermprorx.png'),
    logo: require('../../assets/images/SpecialtyIcons/Logo/dermprorx.png'),
    code: 'DERM',
  },
  {
    id: 'neurology',
    name: 'Neurology',
    short: 'neuro',
    graphic: require('../../assets/images/SpecialtyIcons/neuroprorx.png'),
    logo: require('../../assets/images/SpecialtyIcons/Logo/neuroprorx.png'),
    code: 'NEURO',
  },
  {
    id: 'pulmonology',
    name: 'Pulmonology',
    short: 'pulm',
    graphic: require('../../assets/images/SpecialtyIcons/pulmprorx.png'),
    logo: require('../../assets/images/SpecialtyIcons/Logo/pulmprorx.png'),
    code: 'PULM',
  },
  {
    id: 'allergy',
    name: 'Allergy & Immunology',
    short: 'allergy',
    graphic: require('../../assets/images/SpecialtyIcons/allergyprorx.png'),
    logo: require('../../assets/images/SpecialtyIcons/Logo/allergyprorx.png'),
    code: 'ALLERGY',
  },
  {
    id: 'endocrinology',
    name: 'Endocrinology',
    short: 'endo',
    graphic: require('../../assets/images/SpecialtyIcons/endoprorx.png'),
    logo: require('../../assets/images/SpecialtyIcons/Logo/endoprorx.png'),
    code: 'ENDO',
  },
  {
    id: 'cardiology',
    name: 'Cardiology',
    short: 'cardio',
    graphic: require('../../assets/images/SpecialtyIcons/cardioprorx.png'),
    logo: require('../../assets/images/SpecialtyIcons/Logo/cardioprorx.png'),
    code: 'CARDIO',
  },
  {
    id: 'ophthalmology',
    name: 'Ophthalmology',
    short: 'ophtho',
    graphic: require('../../assets/images/SpecialtyIcons/opthoprorx.png'),
    logo: require('../../assets/images/SpecialtyIcons/Logo/opthoprorx.png'),
    code: 'OPHTHO',
  },
];

export const SUBSCRIPTION_PLANS = [
  {
    id: 'intelligence',
    name: 'Tier 1 — Intelligence',
    tagline: 'Make smarter prescribing decisions with real-time insights.',
    price: 199 as number | null,
    badge: null as string | null,
    isPopular: false,
    isComingSoon: false,
    isEnterprise: false,
    features: [
      'Real-time formulary & coverage visibility',
      'Step therapy requirements & prior treatment insights',
      'Specialty pharmacy routing recommendations',
      'Buy-and-bill eligibility indicators',
      'Payer-specific rules (load-relay)',
      'Patient notifications',
      'Faster decision-making before PA',
    ],
  },
  {
    id: 'authorization',
    name: 'Tier 2 — Authorization',
    tagline: 'Automate prior authorizations and accelerate approvals.',
    price: 249 as number | null,
    badge: 'Most Popular' as string | null,
    isPopular: true,
    isComingSoon: false,
    isEnterprise: false,
    features: [
      'AI-assisted prior authorization creation',
      'One-click PA submission',
      'Real-time status tracking and alerts',
      'Auto-routing to pharmacy or dispensing channel',
      'Patient notifications',
      'Copay assistance matching',
      'Faster approvals with reduced manual effort',
    ],
  },
  {
    id: 'appeals',
    name: 'Tier 3 — Appeals',
    tagline: 'Turn denials into approvals with structured workflows.',
    price: 299 as number | null,
    badge: 'Coming Soon: Tier 3' as string | null,
    isPopular: false,
    isComingSoon: true,
    isEnterprise: false,
    features: [
      'Smart denial analysis',
      'AI-generated appeal letters',
      'Medical necessity templates',
      'Peer-to-peer workflows',
      'Appeal tracking & analytics',
      'Audit-ready documentation',
      'Improve approval success rates',
    ],
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    tagline: 'Tailored workflows and integrations for large practices and health systems.',
    price: null as number | null,
    badge: null as string | null,
    isPopular: false,
    isComingSoon: false,
    isEnterprise: true,
    features: [
      'Seamless integration with existing clinical systems',
      'Unified data flow across workflows',
      'Customizable workflows by specialty, site, or provider group',
      'White-label deployment options',
      'Dedicated onboarding and implementation support',
      'Priority enterprise support and service commitments',
    ],
  },
];

export const ADD_ONS = [
  {
    id: 'iod',
    name: 'Buy & Bill — IOD Module',
    description: 'Enable in-office dispensing workflows',
    price: 49,
    features: [
      'In-office dispensing workflows',
      'Acquisition cost tracking',
      'Billing visibility',
      'Revenue optimization insights',
    ],
  },
];
